version: 2
jobs:
  build:
    docker:
      - image: bananu7/haskell:lts-18.5
    steps:
      - checkout
      - restore_cache:
          keys: 
            - stack-deps-18.5
      - run: stack setup
      - run: stack clean
      - run: stack test --no-run-tests
      - run: stack test
      - save_cache:
          key: stack-deps-18.5
          paths:
            - ".stack-work"
            - "/root/.stack"
