version: 2
jobs:
  build:
    docker:
      - image: bananu7/haskell:0.0.1
    steps:
      - checkout
      - restore_cache:
          keys: 
            - stack-deps-10.5
            - stack-deps-8.21
            - stack-deps
      - run: stack setup
      - run: stack clean
      - run: stack test --no-run-tests
      - run: stack test
      - save_cache:
          key: stack-deps-10.5
          paths:
            - ".stack-work"
            - "/root/.stack"
