version: 2
jobs:
  build:
    docker:
      - image: debian
    steps:
      - checkout
      - run: wget -qO- https://get.haskellstack.org/ | sh
      - run: stack setup
      - run: stack test --no-run-tests

  test:
    docker:
      - image: debian
    steps:
      - run: stack test

workflows:
  version: 2
  master:
    jobs:
      - build
      - test:
          requires:
            - build
