version: 2
jobs:
  build:
    docker:
      - image: debian/wheezy
    steps:
      - wget -qO- https://get.haskellstack.org/ | sh
      - stack setup
      - stack test --no-run-tests

  test:
    docker:
      - image: debian/wheezy
    steps:
      - stack test

workflows:
  version: 2
  master:
    jobs:
      - build
      - test:
          requires:
            - build
